import { AuthProvider } from '@/lib/auth';
import './global.css';

export const metadata = {
  title: 'Welcome to mergejil',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-full min-h-screen bg-black overflow-x-hidden space-y-15">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
