export const PROFILE_DATA = {
  user: {
    name: 'Батболд Д.',
    grade: 'ШУТИС — Мэдээлэл, компьютерийн ухаан',
    completedAt: '2026-08-24',
    totalXP: 370,
  },
  mbti: {
    type: 'INTJ',
    mongolianName: 'Стратег',
    tagline: 'Системчилсэн, урт хугацааны стратегийн сэтгэгч',
    description:
      'Та бие даасан, шинжлэх ухааны сэтгэлгээтэй, цаашдын зорилгоо тодорхой харж чаддаг хүн. Нарийн төвөгтэй асуудлуудыг задлан шинжилж, системт шийдэл олоход ер бусын авьяастай.',
    dimensions: [
      {
        id: 'dim-ie',
        left: 'Introvert (I)',
        right: 'Extravert (E)',
        value: 78,
        side: 'left' as const,
        label: 'I',
      },
      {
        id: 'dim-sn',
        left: 'Sensing (S)',
        right: 'Intuition (N)',
        value: 68,
        side: 'right' as const,
        label: 'N',
      },
      {
        id: 'dim-tf',
        left: 'Thinking (T)',
        right: 'Feeling (F)',
        value: 82,
        side: 'left' as const,
        label: 'T',
      },
      {
        id: 'dim-jp',
        left: 'Judging (J)',
        right: 'Perceiving (P)',
        value: 71,
        side: 'left' as const,
        label: 'J',
      },
    ],
    compatibleTypes: ['ENTJ', 'INFJ', 'ENTP', 'INTP'],
    workStyle: 'Ганцаараа гүнзгий ажиллах, бүтэцтэй орчин, тодорхой зорилготой',
  },
  iq: {
    totalScore: 124,
    label: 'Өндөр',
    percentile: 92,
    description:
      'Хурдан суралцагч, нарийн ажлыг хийж чадна. Олон мэргэжилд амжилттай ажиллах чадвартай.',
    subScores: [
      {
        id: 'iq-sub-logic',
        category: 'Логик',
        score: 88,
        max: 100,
        color: '#2563EB',
      },
      {
        id: 'iq-sub-visual',
        category: 'Орон зай',
        score: 74,
        max: 100,
        color: '#7C3AED',
      },
      {
        id: 'iq-sub-language',
        category: 'Хэл / Дүн шинжилгээ',
        score: 79,
        max: 100,
        color: '#059669',
      },
      {
        id: 'iq-sub-divergent',
        category: 'Бүтээлч / Дивергент',
        score: 65,
        max: 100,
        color: '#D97706',
      },
    ],
  },
  skills: {
    radarData: [
      { subject: 'Техник', value: 82, fullMark: 100 },
      { subject: 'Нийгмийн', value: 54, fullMark: 100 },
      { subject: 'Бүтээлч', value: 61, fullMark: 100 },
      { subject: 'Удирдлага', value: 73, fullMark: 100 },
    ],
    summary:
      'Техникийн болон удирдлагын чадвар хүчтэй. Нийгмийн харилцааны чадварыг хөгжүүлэх шаардлагатай.',
    strengths: [
      'Алгоритм сэтгэлгээ',
      'Системийн дизайн',
      'Стратегийн төлөвлөлт',
      'Асуудал шийдвэрлэлт',
    ],
    gaps: ['Олны өмнө ярих', 'Багийн харилцаа', 'Бүтээлч дизайн'],
  },
  professions: [
    {
      id: 'prof-software',
      rank: 1,
      name: 'Програм хангамжийн инженер',
      englishName: 'Software Engineer',
      matchPct: 94,
      salaryMin: 2500000,
      salaryMax: 6000000,
      demand: 'Маш өндөр',
      demandLevel: 'very-high',
      trend: '↑↑',
      description:
        'Програм хангамж боловсруулах, систем дизайн хийх, багаар ажиллах. Таны INTJ + өндөр логик чадвар + техникийн ур чадвар энэ мэргэжилтэй маш сайн нийцэж байна.',
      skills: [
        'Python / JavaScript',
        'Системийн дизайн',
        'Алгоритм',
        'Git / CI/CD',
      ],
      subjects: ['Математик', 'Физик', 'Мэдээлэл зүй', 'Англи хэл'],
      environment: 'Технологийн компани, стартап, remote ажиллагаа',
    },
    {
      id: 'prof-data',
      rank: 2,
      name: 'Дата шинжээч / AI инженер',
      englishName: 'Data Analyst / AI Engineer',
      matchPct: 91,
      salaryMin: 2500000,
      salaryMax: 7000000,
      demand: 'Маш өндөр',
      demandLevel: 'very-high',
      trend: '↑↑↑',
      description:
        'Өгөгдлийн дүн шинжилгээ, машин сургалт, бизнесийн шийдвэр гаргалтыг дэмжих. Таны аналитик сэтгэлгээ болон логик чадвар энд онцгой давуу тал болно.',
      skills: ['Python / R', 'SQL', 'Machine Learning', 'Tableau / Power BI'],
      subjects: [
        'Математик',
        'Магадлал статистик',
        'Мэдээлэл зүй',
        'Англи хэл',
      ],
      environment:
        'Санхүүгийн байгууллага, технологийн компани, судалгааны төв',
    },
    {
      id: 'prof-architect',
      rank: 3,
      name: 'Системийн архитектор',
      englishName: 'Systems Architect',
      matchPct: 87,
      salaryMin: 3500000,
      salaryMax: 8000000,
      demand: 'Өндөр',
      demandLevel: 'high',
      trend: '↑',
      description:
        'Томоохон мэдээллийн системийг дизайн хийх, техникийн стратеги боловсруулах. Таны INTJ стратегийн сэтгэлгээ болон системт хандлага энд хамгийн сайн илэрнэ.',
      skills: [
        'Cloud Architecture',
        'Microservices',
        'Security Design',
        'Leadership',
      ],
      subjects: ['Математик', 'Физик', 'Мэдээлэл зүй', 'Англи хэл'],
      environment: 'Томоохон IT компани, банк, засгийн газрын байгууллага',
    },
    {
      id: 'prof-pm',
      rank: 4,
      name: 'Бүтээгдэхүүний менежер',
      englishName: 'Product Manager',
      matchPct: 79,
      salaryMin: 2000000,
      salaryMax: 5000000,
      demand: 'Өндөр',
      demandLevel: 'high',
      trend: '↑',
      description:
        'Технологийн бүтээгдэхүүний стратеги, roadmap, баг удирдлага. Таны аналитик + удирдлагын чадвар хослол нь энэ үүрэгт тохирно. Нийгмийн харилцааны чадварыг хөгжүүлэх шаардлагатай.',
      skills: [
        'Product Strategy',
        'Agile / Scrum',
        'User Research',
        'Data Analysis',
      ],
      subjects: ['Математик', 'Нийгэм судлал', 'Мэдээлэл зүй', 'Англи хэл'],
      environment: 'Технологийн компани, стартап, e-commerce',
    },
    {
      id: 'prof-researcher',
      rank: 5,
      name: 'Судлаач / Эрдэм шинжилгээч',
      englishName: 'Research Scientist',
      matchPct: 74,
      salaryMin: 1800000,
      salaryMax: 4500000,
      demand: 'Дунд',
      demandLevel: 'medium',
      trend: '→',
      description:
        'Шинжлэх ухааны судалгаа, нийтлэл, нээлт. Таны INTJ хувь хүний онцлог судалгааны ажилд маш тохиромжтой боловч Монголын хөдөлмөрийн зах зээлд хязгаарлагдмал боломжтой.',
      skills: [
        'Судалгааны арга зүй',
        'Статистик',
        'Нийтлэл бичих',
        'Тэтгэлэг авах',
      ],
      subjects: ['Математик', 'Физик', 'Хими', 'Биологи', 'Англи хэл'],
      environment: 'Их сургууль, судалгааны хүрээлэн, олон улсын байгууллага',
    },
    {
      id: 'prof-security',
      rank: 6,
      name: 'Кибер аюулгүй байдлын инженер',
      englishName: 'Cybersecurity Engineer',
      matchPct: 72,
      salaryMin: 3000000,
      salaryMax: 7500000,
      demand: 'Өндөр',
      demandLevel: 'high',
      trend: '↑↑',
      description:
        'Мэдээллийн системийн эрсдэлийг тодорхойлж, хамгаалалтын шийдэл боловсруулах. Таны нарийн дүн шинжилгээ хийх чадвар, системт хандлага энэ чиглэлд сайн тохирно.',
      skills: [
        'Network Security',
        'Penetration Testing',
        'Risk Assessment',
        'Cloud Security',
      ],
      subjects: ['Математик', 'Мэдээлэл зүй', 'Физик', 'Англи хэл'],
      environment: 'Банк санхүү, IT компани, засгийн газрын байгууллага',
    },
  ],
  universities: [
    {
      id: 'uni-shutis',
      name: 'ШУТИС',
      fullName: 'Шинжлэх ухаан технологийн их сургууль',
      programs: [
        'Мэдээлэл, компьютерийн ухаан',
        'Програм хангамж',
        'Мэдээллийн систем',
      ],
      matchScore: 96,
      location: 'Улаанбаатар',
      country: 'Монгол' as const,
      type: 'Улсын',
      tuition: '2,800,000 – 3,500,000₮/жил',
      highlight: 'IT мэргэжлийн хамгийн том сургуультай',
      scholarship:
        'Улсын тэтгэлэгт хөтөлбөр болон онц дүнгийн тэтгэлэг байдаг. Дэлгэрэнгүй мэдээллийг сургуулийн Оюутны хэргийн албанаас лавлах боломжтой.',
    },
    {
      id: 'uni-muis',
      name: 'МУИС',
      fullName: 'Монгол Улсын Их Сургууль',
      programs: ['Мэдээллийн технологи', 'Математик', 'Физик'],
      matchScore: 88,
      location: 'Улаанбаатар',
      country: 'Монгол' as const,
      type: 'Улсын',
      tuition: '2,400,000 – 3,200,000₮/жил',
      highlight: 'Монголын хамгийн нэр хүндтэй их сургууль',
      scholarship:
        'Сурлагын өндөр амжилттай болон нийгмийн эмзэг бүлгийн оюутанд зориулсан төрөл бүрийн тэтгэлэг олгодог. Элссэний дараа Оюутны хэргийн газраас дэлгэрэнгүй лавлах боломжтой.',
    },
    {
      id: 'uni-mjis',
      name: 'МЖИС',
      fullName: 'Монгол Японы Их Сургууль',
      programs: ['IT менежмент', 'Програм хангамж', 'Мэдээллийн систем'],
      matchScore: 82,
      location: 'Улаанбаатар',
      country: 'Монгол' as const,
      type: 'Хамтарсан',
      tuition: '3,500,000 – 4,800,000₮/жил',
      highlight: 'Японы технологийн стандарт, олон улсын гэрчилгээ',
      scholarship:
        'Японы засгийн газар болон хамтран ажилладаг байгууллагуудын хэсэгчилсэн тэтгэлэгт хөтөлбөр байдаг. Элсэлтийн товчооноос дэлгэрэнгүй мэдээлэл авах боломжтой.',
    },
    {
      id: 'uni-num',
      name: 'NUM',
      fullName: 'National University of Mongolia',
      programs: ['Computer Science', 'Engineering', 'Mathematics'],
      matchScore: 77,
      location: 'Улаанбаатар',
      country: 'Монгол' as const,
      type: 'Улсын',
      tuition: '2,200,000 – 3,000,000₮/жил',
      highlight: 'Англи хэлний сургалт, олон улсын харилцаа',
      scholarship:
        'Олон улсын хамтарсан хөтөлбөрийн тэтгэлэг болон дотоод онц дүнгийн тэтгэлэг байдаг. Сургуулийн элсэлтийн албанаас дэлгэрэнгүй лавлах шаардлагатай.',
    },
    {
      id: 'uni-otgontenger',
      name: 'Отгонтэнгэр ИС',
      fullName: 'Отгонтэнгэр Их Сургууль',
      programs: ['Мэдээллийн технологи', 'Бизнесийн удирдлага'],
      matchScore: 70,
      location: 'Улаанбаатар',
      country: 'Монгол' as const,
      type: 'Хувийн',
      tuition: '2,000,000 – 2,800,000₮/жил',
      highlight: 'Уян хатан хөтөлбөр, ажилтай хослуулан суралцах боломж',
      scholarship:
        'Хувийн сургуулийн хөнгөлөлттэй төлбөрийн систем, шилдэг элсэгчдэд зориулсан хөнгөлөлт үзүүлдэг. Сургуулийн элсэлтийн албанаас нарийвчилсан нөхцөлийг лавлана.',
    },
    {
      id: 'uni-kaist',
      name: 'KAIST',
      fullName: 'Korea Advanced Institute of Science and Technology',
      programs: ['Computer Science', 'AI Engineering', 'Software Systems'],
      matchScore: 90,
      location: 'Өмнөд Солонгос',
      country: 'Гадаад' as const,
      type: 'Улсын',
      tuition: '$4,000 – 6,000/жил (тэтгэлэгтэй)',
      highlight:
        'Азийн тэргүүлэх инженерийн их сургууль, монгол оюутанд тэтгэлэг олгодог',
      scholarship:
        'Солонгосын засгийн газрын GKS тэтгэлэг болон сургуулийн дотоод тэтгэлэгт хамрагдах боломжтой. Өргөдлийг Солонгос дахь Монгол Улсын Элчин сайдын яамаар дамжуулж бүрдүүлдэг.',
    },
    {
      id: 'uni-nus',
      name: 'NUS',
      fullName: 'National University of Singapore',
      programs: ['Computer Science', 'Data Science', 'Information Systems'],
      matchScore: 85,
      location: 'Сингапур',
      country: 'Гадаад' as const,
      type: 'Улсын',
      tuition: '$25,000 – 30,000/жил',
      highlight: 'Азийн №1 их сургууль (QS ranking)',
      scholarship:
        'Гадаад оюутанд зориулсан хувийн болон сургуулийн тэтгэлэгт сангаас дэмжлэг авах боломжтой. Дэлгэрэнгүй мэдээллийг сургуулийн Admissions Office-с лавлана.',
    },
    {
      id: 'uni-tokyotech',
      name: 'Tokyo Tech',
      fullName: 'Tokyo Institute of Technology',
      programs: ['Computer Science', 'Information Engineering'],
      matchScore: 80,
      location: 'Япон',
      country: 'Гадаад' as const,
      type: 'Улсын',
      tuition: '¥535,800/жил (~13 сая₮)',
      highlight: 'MEXT тэтгэлэгтэй, монгол оюутанд нээлттэй',
      scholarship:
        'Японы Боловсролын яамны MEXT тэтгэлэг жил бүр Монголын БШУЯ-аар дамжин зарлагддаг. Бүрдүүлэх материалын мэдээллийг БШУЯ-наас авах боломжтой.',
    },
    {
      id: 'uni-tsinghua',
      name: 'Tsinghua',
      fullName: 'Tsinghua University',
      programs: ['Computer Science', 'Software Engineering', 'AI'],
      matchScore: 88,
      location: 'Хятад',
      country: 'Гадаад' as const,
      type: 'Улсын',
      tuition: '$3,500 – 5,000/жил (тэтгэлэгтэй)',
      highlight: 'Азийн тэргүүлэх их сургууль, CSC тэтгэлэгтэй',
      scholarship:
        'Хятадын засгийн газрын CSC тэтгэлэг болон Күнзийн институтын тэтгэлэгт хөтөлбөрт хамрагдах боломжтой. Өргөдлийг Хятад дахь ЭСЯ эсвэл сургуулийн олон улсын оюутны албанд гаргана.',
    },
    {
      id: 'uni-hse',
      name: 'HSE',
      fullName: 'National Research University Higher School of Economics',
      programs: ['Computer Science', 'Data Science', 'Applied Mathematics'],
      matchScore: 75,
      location: 'Орос',
      country: 'Гадаад' as const,
      type: 'Улсын',
      tuition: 'ОХУ-ын засгийн газрын тэтгэлэгтэй',
      highlight:
        'Оросын засгийн газрын тэтгэлэг олгодог, монгол оюутанд танил орчин',
      scholarship:
        'ОХУ-ын засгийн газрын квот тэтгэлэг жил бүр Монголын БШУЯ-аар дамжин зарлагддаг. Дэлгэрэнгүй мэдээллийг БШУЯ-ны гадаад харилцааны хэлтэс эсвэл ОХУ-ын Элчин сайдын яамнаас авна.',
    },
  ],
  workEnvironments: [
    {
      id: 'env-remote',
      icon: '💻',
      title: 'Remote / Цахим ажиллагаа',
      match: 95,
      desc: 'Гэрт буюу хаанаас ч ажиллах боломж',
    },
    {
      id: 'env-startup',
      icon: '🚀',
      title: 'Стартап',
      match: 88,
      desc: 'Хурдан шийдвэр, олон үүрэг, хувьсал',
    },
    {
      id: 'env-tech',
      icon: '🏢',
      title: 'Технологийн компани',
      match: 85,
      desc: 'Бүтэцтэй орчин, мэргэжлийн өсөлт',
    },
    {
      id: 'env-research',
      icon: '🔬',
      title: 'Судалгааны байгууллага',
      match: 79,
      desc: 'Гүнзгий судалгаа, шинэ нээлт',
    },
  ],
  collaborationStyles: [
    {
      id: 'collab-async',
      style: 'Async харилцаа',
      desc: 'Цахим бичиг, документ, тодорхой даалгавар',
      match: 'Маш тохиромжтой',
    },
    {
      id: 'collab-small',
      style: 'Жижиг баг (2-5 хүн)',
      desc: 'Мэргэжилтнүүдийн нягт хамтын ажиллагаа',
      match: 'Тохиромжтой',
    },
    {
      id: 'collab-independent',
      style: 'Бие даасан ажил',
      desc: 'Ганцаараа гүнзгий ажиллах, бие даасан шийдвэр',
      match: 'Маш тохиромжтой',
    },
    {
      id: 'collab-large',
      style: 'Том баг / олон нийт',
      desc: 'Олон хүнтэй байнгын харилцаа',
      match: 'Бага тохиромжтой',
    },
  ],
  roadmap: [
    {
      id: 'roadmap-phase1',
      phase: 1,
      title: 'Одоогийн: Үнэлгээ & Карьер тохирол',
      status: 'current' as const,
      color: 'bg-primary',
      duration: '1–2 долоо хоног',
      goal: 'Өөрийн сонирхол, давуу талаа мэдэж, програм бүтээдэг хүн яг юу хийдгийг ойлгох.',
      challenge:
        'Өдөр бүр ашигладаг 3 апп сонгоод, тус бүр нь ямар асуудлыг шийддэгийг нэг өгүүлбэрээр бичээрэй.',
      items: [
        'MBTI + IQ + Ур чадварын тест',
        'AI карьерийн профайл',
        'Их сургуулийн санал',
        'Хөдөлмөрийн зах зээлийн мэдээлэл',
      ],
      xp: 370,
    },
    {
      id: 'roadmap-phase2',
      phase: 2,
      title: 'Q2 2026: AI Даалгавар & Суралцах зам',
      status: 'upcoming' as const,
      color: 'bg-info',
      duration: '4–6 долоо хоног',
      goal: 'Кодын суурь ойлголтыг сурч, компьютерээр энгийн даалгавар хийлгэж чаддаг болох.',
      challenge:
        'Өөрийн нэр, нас, дуртай хичээлийг асуугаад мэндчилгээ гаргадаг жижиг програм бүтээгээрэй.',
      items: [
        'Claude API-р автомат даалгавар үүсгэх',
        'Monaco Editor + Python sandbox',
        'XP суурь алгоритм',
        'Мэргэжил тус бүрийн суралцах зам',
      ],
      xp: 500,
    },
    {
      id: 'roadmap-phase3',
      phase: 3,
      title: 'Q3 2026: AI Ментор & Кодын дүн шинжилгээ',
      status: 'planned' as const,
      color: 'bg-violet-500',
      duration: '6–8 долоо хоног',
      goal: 'Сурсан чадваруудаа нийлүүлж, бусад хүн ашиглаж болох жижиг төсөл бүтээх.',
      challenge:
        'Сургуулийн даалгавраа тэмдэглэж, хийснээ дарж дуусгадаг вэб хуудас бүтээгээрэй.',
      items: [
        'Streaming chat интерфейс',
        'Алдааны хэв маягийг илрүүлэх',
        'Алхам алхмаар удирдамж',
        'Хувийн суралцах тэмдэглэл',
      ],
      xp: 800,
    },
    {
      id: 'roadmap-phase4',
      phase: 4,
      title: 'Q4 2026: Micro Simulation + XP Систем',
      status: 'planned' as const,
      color: 'bg-accent',
      duration: '2–3 сар',
      goal: 'Илүү том төсөл төлөвлөж, багаар ажиллан, хийсэн бүтээлээ бусдад танилцуулж сурах.',
      challenge:
        '2–3 найзтайгаа баг болж сургуулийн нэг асуудлыг шийдэх аппын загвар гарган танилцуулаарай.',
      items: [
        'Компанийн хамтын ажиллагааны симуляц',
        'Болор гэрчилгээ',
        'Streak систем',
        'Leaderboard & Badge',
      ],
      xp: 1200,
    },
  ],
};
